image: mrdevfree/alpine-node-yarn:latest

before_script:
  - echo -e "//registry.npmjs.org/:_authToken=${NPM_INSTALL_TOKEN}\n@tdk:registry=https://registry.npmjs.org" > ~/.npmrc

stages:
  - build
  - test
  - publish
  - docs

deps build:
  stage: build
  script:
    - source ./scripts/prepare
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 week

lint:
  stage: test
  script:
    - yarn run lint

unit test:
  stage: test
  script:
    - yarn run test

coverage:
  stage: test
  script:
    - yarn run coverage

npm publish:
  stage: publish
  script:
    - yarn run release
  only:
    - tags

# docs:
#   stage: docs
#   script:
#     - "curl --request POST --form token=$TOKEN --form ref=master https://gitlab.co"
#   only:
#     - tags
